joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - J_1
    - J_2
    - J_4
    - J_6
    - J_7
    - J_10
    - J_12
    - J_14
    - J_15
    - J_16
  
    
    
    


  
  
  
    
